title: 玻璃杯公司
email: info@example.com
description: "专注于生产高质量玻璃杯的公司"
baseurl: "" # 项目的基础路径
url: "http://example.com" # 网站的URL
twitter_username: yourTwitterHandle
github_username:  yourGitHubHandle

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed